name: Bug Report
description: Report a bug in PkgWatch
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of PkgWatch is affected?
      options:
        - CLI (@pkgwatch/cli)
        - GitHub Action (@pkgwatch/action)
        - API
        - Landing Page / Dashboard
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: "Run `pkgwatch --version` or check action version"
      placeholder: "e.g., 1.2.0"
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What should have happened instead?
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run `pkgwatch check ...`
        2. ...
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "OS, Node version, CI environment, error logs, etc."
