name: Feature Request
description: Suggest an improvement or new feature
labels: ["enhancement"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Which component?
      description: What area of PkgWatch would this affect?
      options:
        - CLI (@pkgwatch/cli)
        - GitHub Action (@pkgwatch/action)
        - API
        - Scoring Algorithm
        - New Ecosystem Support
        - Other
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case or pain point
      placeholder: "I'm trying to ... but currently ..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think it should work?
  - type: textarea
    id: workaround
    attributes:
      label: Current workaround
      description: How are you solving this today, if at all?
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other information that might be helpful
